//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extender {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extender.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD FILE.
        /// </summary>
        internal static string AddAttachmentText {
            get {
                return ResourceManager.GetString("AddAttachmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arguments(separator ;).
        /// </summary>
        internal static string ArgumentListPlaceholder {
            get {
                return ResourceManager.GetString("ArgumentListPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument list.
        /// </summary>
        internal static string ArgumentListTitle {
            get {
                return ResourceManager.GetString("ArgumentListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string CancelTitle {
            get {
                return ResourceManager.GetString("CancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active connection profiles:.
        /// </summary>
        internal static string ConnectionProfiles {
            get {
                return ResourceManager.GetString("ConnectionProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credentials.
        /// </summary>
        internal static string CredentialsTitle {
            get {
                return ResourceManager.GetString("CredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DNS.
        /// </summary>
        internal static string DnsPageTitle {
            get {
                return ResourceManager.GetString("DnsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter domain name....
        /// </summary>
        internal static string DnsPlaceholder {
            get {
                return ResourceManager.GetString("DnsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FAIL.
        /// </summary>
        internal static string FailedHttpResponseTitle {
            get {
                return ResourceManager.GetString("FailedHttpResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messaging Failed.
        /// </summary>
        internal static string FailedMail {
            get {
                return ResourceManager.GetString("FailedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path to process .exe file....
        /// </summary>
        internal static string FileNamePlaceholder {
            get {
                return ResourceManager.GetString("FileNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process file path.
        /// </summary>
        internal static string FileNameTitle {
            get {
                return ResourceManager.GetString("FileNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GET.
        /// </summary>
        internal static string GetTitle {
            get {
                return ResourceManager.GetString("GetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here local IP....
        /// </summary>
        internal static string HostPlaceholder {
            get {
                return ResourceManager.GetString("HostPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTTP.
        /// </summary>
        internal static string HttpCrudTitle {
            get {
                return ResourceManager.GetString("HttpCrudTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error via request was detected!.
        /// </summary>
        internal static string HttpResponseError {
            get {
                return ResourceManager.GetString("HttpResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Http Response.
        /// </summary>
        internal static string HttpResponseTitle {
            get {
                return ResourceManager.GetString("HttpResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на file installed .
        /// </summary>
        internal static string InstalledPath {
            get {
                return ResourceManager.GetString("InstalledPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Server:.
        /// </summary>
        internal static string IsServerTitle {
            get {
                return ResourceManager.GetString("IsServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here json....
        /// </summary>
        internal static string JsonPlaceholder {
            get {
                return ResourceManager.GetString("JsonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на uri is invalid.
        /// </summary>
        internal static string LoadFileError {
            get {
                return ResourceManager.GetString("LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP.
        /// </summary>
        internal static string MailPageTitle {
            get {
                return ResourceManager.GetString("MailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail was sended!.
        /// </summary>
        internal static string MailSended {
            get {
                return ResourceManager.GetString("MailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here content of mail (may be html)....
        /// </summary>
        internal static string MessageMailPlaceholder {
            get {
                return ResourceManager.GetString("MessageMailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network.
        /// </summary>
        internal static string MultiNetTitle {
            get {
                return ResourceManager.GetString("MultiNetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web-path to file....
        /// </summary>
        internal static string NetPagePlaceholder {
            get {
                return ResourceManager.GetString("NetPagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LOAD.
        /// </summary>
        internal static string NetPageTitle {
            get {
                return ResourceManager.GetString("NetPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network access:.
        /// </summary>
        internal static string NetworkAccess {
            get {
                return ResourceManager.GetString("NetworkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network.
        /// </summary>
        internal static string NetworkPageTitle {
            get {
                return ResourceManager.GetString("NetworkPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no access.
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Internet connection!!!.
        /// </summary>
        internal static string NoNetworkAccess {
            get {
                return ResourceManager.GetString("NoNetworkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password/Username(via ;).
        /// </summary>
        internal static string PasswordUserNamePlaceholder {
            get {
                return ResourceManager.GetString("PasswordUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физическая память (в байтах).
        /// </summary>
        internal static string PhysicalMemoryTitle {
            get {
                return ResourceManager.GetString("PhysicalMemoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here local port....
        /// </summary>
        internal static string PortPlaceholder {
            get {
                return ResourceManager.GetString("PortPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на POST.
        /// </summary>
        internal static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время исполнения кода.
        /// </summary>
        internal static string ProcessCodeExecutionTitle {
            get {
                return ResourceManager.GetString("ProcessCodeExecutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время завершения процесса.
        /// </summary>
        internal static string ProcessExitTimeTitle {
            get {
                return ResourceManager.GetString("ProcessExitTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор процесса.
        /// </summary>
        internal static string ProcessIdTitle {
            get {
                return ResourceManager.GetString("ProcessIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process information:.
        /// </summary>
        internal static string ProcessInfo {
            get {
                return ResourceManager.GetString("ProcessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KILL.
        /// </summary>
        internal static string ProcessKill {
            get {
                return ResourceManager.GetString("ProcessKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина запустившая процесс.
        /// </summary>
        internal static string ProcessMachineNameTitle {
            get {
                return ResourceManager.GetString("ProcessMachineNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок окна процесса.
        /// </summary>
        internal static string ProcessMainWindowTitle {
            get {
                return ResourceManager.GetString("ProcessMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя процесса.
        /// </summary>
        internal static string ProcessNameTitle {
            get {
                return ResourceManager.GetString("ProcessNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PROCESS.
        /// </summary>
        internal static string ProcessPageTitle {
            get {
                return ResourceManager.GetString("ProcessPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритет процесса.
        /// </summary>
        internal static string ProcessPriorityTitle {
            get {
                return ResourceManager.GetString("ProcessPriorityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отвечает ли процесс.
        /// </summary>
        internal static string ProcessRespondingTitle {
            get {
                return ResourceManager.GetString("ProcessRespondingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Process.
        /// </summary>
        internal static string ProcessStart {
            get {
                return ResourceManager.GetString("ProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GO.
        /// </summary>
        internal static string ProcessStartButton {
            get {
                return ResourceManager.GetString("ProcessStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время запуска процесса.
        /// </summary>
        internal static string ProcessStartTimeTitle {
            get {
                return ResourceManager.GetString("ProcessStartTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время исполнения кода у потока.
        /// </summary>
        internal static string ProcessThreadCodeExecutionTitle {
            get {
                return ResourceManager.GetString("ProcessThreadCodeExecutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор потока процесса.
        /// </summary>
        internal static string ProcessThreadIdTitle {
            get {
                return ResourceManager.GetString("ProcessThreadIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритет потока процесса.
        /// </summary>
        internal static string ProcessThreadPriorityTitle {
            get {
                return ResourceManager.GetString("ProcessThreadPriorityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние потока процесса.
        /// </summary>
        internal static string ProcessThreadStateTitle {
            get {
                return ResourceManager.GetString("ProcessThreadStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счетчик потоков процесса.
        /// </summary>
        internal static string ProcessThreadsTitle {
            get {
                return ResourceManager.GetString("ProcessThreadsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обшее время потока процесса.
        /// </summary>
        internal static string ProcessThreadTotalExecutionTitle {
            get {
                return ResourceManager.GetString("ProcessThreadTotalExecutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина ожидания потока процесса.
        /// </summary>
        internal static string ProcessThreadWaitReasonTitle {
            get {
                return ResourceManager.GetString("ProcessThreadWaitReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ordered processes:.
        /// </summary>
        internal static string ProcessTitle {
            get {
                return ResourceManager.GetString("ProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее время процесса.
        /// </summary>
        internal static string ProcessTotalExecutionTitle {
            get {
                return ResourceManager.GetString("ProcessTotalExecutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PUT.
        /// </summary>
        internal static string PutTitle {
            get {
                return ResourceManager.GetString("PutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here remote IP....
        /// </summary>
        internal static string RemoteHostPlaceholder {
            get {
                return ResourceManager.GetString("RemoteHostPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here remote port....
        /// </summary>
        internal static string RemotePortPlaceholder {
            get {
                return ResourceManager.GetString("RemotePortPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RESPONSE STRING.
        /// </summary>
        internal static string ResponseContentTitle {
            get {
                return ResourceManager.GetString("ResponseContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HEADERS.
        /// </summary>
        internal static string ResponseHeadersTitle {
            get {
                return ResourceManager.GetString("ResponseHeadersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STATUS CODE.
        /// </summary>
        internal static string ResponseStatusCodeTitle {
            get {
                return ResourceManager.GetString("ResponseStatusCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REQUEST URI.
        /// </summary>
        internal static string ResponseUriTitle {
            get {
                return ResourceManager.GetString("ResponseUriTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Runtime.
        /// </summary>
        internal static string RuntimePageTitle {
            get {
                return ResourceManager.GetString("RuntimePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Runtime.
        /// </summary>
        internal static string RuntimeTitle {
            get {
                return ResourceManager.GetString("RuntimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SAVE TO CLIPBOARD.
        /// </summary>
        internal static string SaveClipboard {
            get {
                return ResourceManager.GetString("SaveClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT FILE CONTENT.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SEND MAIL.
        /// </summary>
        internal static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SEND REQUEST.
        /// </summary>
        internal static string SendModel {
            get {
                return ResourceManager.GetString("SendModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here data to send (Server as Response,Client as Request)....
        /// </summary>
        internal static string SocketDataPlaceholder {
            get {
                return ResourceManager.GetString("SocketDataPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Socket error was detected!.
        /// </summary>
        internal static string SocketError {
            get {
                return ResourceManager.GetString("SocketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TCP.
        /// </summary>
        internal static string SocketPageTitle {
            get {
                return ResourceManager.GetString("SocketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session response.
        /// </summary>
        internal static string SocketResponseTitle {
            get {
                return ResourceManager.GetString("SocketResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CONNECT.
        /// </summary>
        internal static string SocketStartTitle {
            get {
                return ResourceManager.GetString("SocketStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SUCCESS.
        /// </summary>
        internal static string SuccessHttpResponseTitle {
            get {
                return ResourceManager.GetString("SuccessHttpResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success Communication.
        /// </summary>
        internal static string SuccessMail {
            get {
                return ResourceManager.GetString("SuccessMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TCP.
        /// </summary>
        internal static string Tcp {
            get {
                return ResourceManager.GetString("Tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here JWT-token....
        /// </summary>
        internal static string TokenPlaceholder {
            get {
                return ResourceManager.GetString("TokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emails to send (separator ,).
        /// </summary>
        internal static string ToPlaceholder {
            get {
                return ResourceManager.GetString("ToPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UDP.
        /// </summary>
        internal static string Udp {
            get {
                return ResourceManager.GetString("Udp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter here request uri....
        /// </summary>
        internal static string UriPlaceholder {
            get {
                return ResourceManager.GetString("UriPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use credentials.
        /// </summary>
        internal static string UseCredentials {
            get {
                return ResourceManager.GetString("UseCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виртуальная память (в байтах).
        /// </summary>
        internal static string VirtualMemoryTitle {
            get {
                return ResourceManager.GetString("VirtualMemoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAX,MIN,HIDDEN,DEFAULT.
        /// </summary>
        internal static string WindowStylePlaceholder {
            get {
                return ResourceManager.GetString("WindowStylePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Window Style.
        /// </summary>
        internal static string WindowStyleTitle {
            get {
                return ResourceManager.GetString("WindowStyleTitle", resourceCulture);
            }
        }
    }
}
